### ISSUE TITLE
zte blade a610 same kernel

### ISSUE THREAD

**Issue by bgman111111** [MediatekAndroidDevelopers/android_kernel_coolpad_note3#2]
hi i see that note3lite and zte blade a610 are same kernel. Please help port it to latest kernel. I want compile lineage 17, lineage 16, lineage 15. I have stok kernel from zte that is android 6. But i have idea how to be port. I need hacker to write it.

**Comment by fire855** [comment]
Hi, If you have the sources for the stock kernel, you can try to add the drivers for your phone to this (or other mt6735) kernel.
Sorry but we don't have time for doing this for you.
