### ISSUE TITLE
Re-open 

### ISSUE THREAD

**Issue by bgman111111** [MediatekAndroidDevelopers/android_kernel_coolpad_note3#3]
HI guys i forget i my password so i reset it. 

PLease help. Other day i send email to mediatekandroiddevelkipoers in gmailk100. PLease i need help my mother upgrade lineage to new 16. it has zte blade a610 and other day it start restart. It has 6735.I don't know how to port drivers, include i try it, but it comment errors. If you don't belive me, look here: I get my friend peturbg password and put this: https://bgzashtita.es/git/Android-smartphones/zte/blade-a610

It don't have coolpad3 note port to zte blade a610 drivers, becouse i didn't put it in myu friend gitlab. Dissapointent how linus tarval has made kernel. So forcing peoples to buy new smartphones. It is not difficult that linus to make automatic portable. WHen person want to upgrade kernel to has upgrade function. So upgrading from 3.10 to latest kernel to upgrade. What version you come ok then move this drivers here and all code will be apply atomatic. This is linus torvald FAULT that now i need to seek for help in mediatekandroiddevelopers to help me. I don't want to disturb them but i want to upgrade kernel. Anybody can't be judge, police, so please help me. Includei try patch stock kernel and after first patch or some patch from git cherry it comment missing drivers. So patching kernel too don't work. I woffer 50 euros for who make new kerne100 for zte blade. Please help me. and i offer too 30 euros for who make device tree blob, vendor tree blob 100 
https://github.com/MediatekAndroidDevelopers/android_kernel_coolpad_note3/issues/2

**Comment by dragonpt** [comment]
Yeah Blame Mr. Linus for your s* phone company not complying with GPL...
